CREATE TABLE IF NOT EXISTS cards (
    ID SERIAL PRIMARY KEY,
    Bank VARCHAR(255) NOT NULL,
    Type VARCHAR(255) NOT NULL,
    Nomer VARCHAR(255) NOT NULL,
    Due VARCHAR(255) NOT NULL,
    UserID VARCHAR(255),
);